### ISSUE TITLE
Could you please add a function to get access and refresh tokens by passing code parameter?

### ISSUE THREAD

**Issue by JacquilineJaison** [sagarrabadiya/outlook-php#5]
I don't want to use Session for storing tokens and also don't want to use it for eventAuthorizer.
Also,I want to use a function to get tokens by passing in the code parameter (which too don't want to obtain from $_GET method).

**Comment by sagarrabadiya** [comment]
I dont think I should add that method, that is very unusual and also very error prone, because it might be possible that scopes or other parameters doesnt match when fetching access token, all params should be same in both request for getting code and getting access token, for this kind of custom behavior i think you should create your own authorizer class which extends package's authorizer class and add that method in your class so you can use it.. 🙂
